config/routes.rb
Rails.application.routes.draw do
  get "sales/new"

  root "welcome#index"
  resources :foods do
    resources :comments
  end
  
  resources :categories
  resources :cart_items
  resources :carts
  resources :administrator
  resources :sales
  resources :employee do
    resources :orders
  end

  get "display/:option" => "sales#display", as: "display"
  get "login" => "welcome#new"
  get "/payment/processed" => "checkout#create", as: :get_payment_completed
  get "admin" => "administrator#show", as: :dashboard
  get "admin/foods" => "administrator#food_index", as: :admin_foods
  get "admin/orders" => "administrator#order_index", as: :admin_orders
  get "admin/employee" => "administrator#employee_index", as: :admin_employee
  get "admin/sales" => "administrator#sale_index", as: :admin_sales
  get "admin/categories" => "administrator#category_index",
      as: :admin_categories
  post "login" => "welcome#create"
  post "checkout" => "checkout#show", as: :checkout
  post "carts/checkout" => "carts#checkout", as: :cart_checkout
  post "payment" => "checkout#create", as: :payment
  post "/foods/:food_id/comments(.:format)" => "comments#create",
       as: :create_food_comment
  post "/payment/processed" => "checkout#create", as: :payment_completed
  patch "order_status" => "administrator#update", as: :order_status
  patch "/foods/:food_id/edit_status" => "foods#edit_status", as: :edit_status
  delete "logout" => "welcome#destroy"
  delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
    before_action :check_if_admin, only: [:show, :update]

  def show
    @orders = Order.all.paginate(page: params[:page], per_page: 10)
  end

  def food_index
    @foods = Food.all.order(created_at: :desc)
    respond_to do |format|
      format.js
    end
  end

  def order_index
    @orders = Order.all.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.js
    end
  end

  def employee_index
    @employees = Employee.all.paginate(page: params[:page],
                               per_page: 10).order(created_at: :desc)
    respond_to do |format|
      format.js
    end
  end

  def category_index
    @categories = Category.all.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.js
    end
  end

  def sale_index
    @items = []
    Food.all.each do |food|
      @items << food if food.sales[:status]
    end
    respond_to do |format|
      format.js
    end
  end

  def update
    @title = "orders"
    @orders = Order.all.paginate(page: params[:page], per_page: 10)
    @status = params["order"]["Status"]
    @order_id = params["order_id"]
    @order = Order.find(@order_id)
    @order.update(Status: @status)
    StatusWorker.perform_async(@order_id)
    redirect_to dashboard_path
  end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/views/administrator/_categories.html.erb
<div class="panel header-panel flow-text z-depth-3">
  <div id="title">All Categories</div>
</div>
<div class="full-height scroll-bar">
  <div class="header">
    <div class="row">
  </div>

  </div><!--end of header-->
  <div class="body">
    <table class="striped">
    <thead>
      <tr>
        <th data-field="id">Name</th>
        <th data-field="name">Description</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <a href = "/>">
        <tr>
          <td><%=link_to "#{category.title}", edit_category_path(category.id) %></td>
          <td><%= category.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div><!--end of header-->

  <div class="footer">
    <div class="row">
      <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
          <i class="large material-icons">add</i>
        </a>
        <ul>
          <li><a href="/categories/new" class="btn-floating red"><i class="material-icons">web</i></a></li>
        </ul>
      </div>
    </div>
  </div>

</div>

app/views/administrator/_employee.html.erb
<div class="panel header-panel flow-text z-depth-3">
  <div id="title">All Employees</div>
  </div>
<div class="full-height scroll-bar">
  <table class="striped">
    <thead>
      <tr>
          <th></th>
          <th>Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Date joined</th>
          <th></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= link_to "#{employee.ename}" , employee_path(employee.id)%></td>
          <td><%= link_to "#{employee.ephone}" , employee_path(employee.id)%></td>
          <td><%= employee.email %></td>
          <td><%= employee.created_at.strftime("%Y - %e - %d") %></td>
          <td>
            <%= button_to employee_path(employee.id), :class => "clear-button", method: :delete, data: { :confirm=>'You sure?' } do %>
              <i class="material-icons">clear</i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/administrator/_foods.html.erb
<div class="panel header-panel flow-text z-depth-3">
      <div id="title">All Foods</div>
    </div>
<div class="full-height scroll-bar">
	<div class="header">
			<div class="row">
				<div class="input-field col s6">
			    <select class="select_box select_field" style="display:block">
			      <option value="0" selected>Sort by status</option>
			      <option value="/foods" >Available</option>
			      <option value="/">Not available</option>
			    </select>
			  </div>

				<div class="input-field col s6">
          <i class="material-icons prefix">search</i>
          <input id="icon_prefix" type="text" class="validate">
          <label for="icon_prefix">Type in food name</label>
				</div>
			</div>

	</div><!--end of header-->
	<div class="body">
		<table class="striped">
		<thead>
			<tr>
					<th data-field="id">Name</th>
					<th data-field="name">Description</th>
					<th data-field="price">Item Price</th>
					<th data-field="price">Category</th>
					<th data-field="price">Available ?</th>
					<th data-field="price">Updated</th>
					<th data-field="price"></th>
			</tr>
		</thead>

		<tbody>
			<% @foods.each do |food| %>
				<a href = "/>">
				<tr>
					<td><%=link_to "#{food.name}", edit_food_path(food.id) %></td>
					<td><%= food.description %></td>
					<td><%= food.price %></td>
					<td><%= !food.category.nil? ? food.category.title : "none yet" %></td>
					<td>
						<div class="switch">
							<label>
								No
								<input class="food_status" type="checkbox" data-status="<%= food.status %>" data-foodid="<%= food.id %>">
								<span class="lever"></span>
								Yes
							</label>
						</div>
					</td>
					<td><%= food.updated_at.strftime("%Y %e %d") %></td>
					<td>
						<%= button_to food_path(food.id), :class => "clear-button", method: :delete do %>
							<i class="material-icons">clear</i>
						<% end %>
					</td>
				</tr>

			<% end %>
		</tbody>
	</table>
	</div><!--end of header-->
	<div class="footer">
		<div class="row">
		  <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
		    <a class="btn-floating btn-large red">
		      <i class="large material-icons">add</i>
		    </a>
		    <ul>
		      <li><a href="/foods/new" class="btn-floating yellow darken-1"><i class="material-icons">settings_input_svideo</i></a></li>
		    </ul>
		  </div>
		</div>
	</div><!--end of header-->

</div>

app/views/administrator/_orders.html.erb
<div class="panel header-panel flow-text z-depth-3">
  <div id="title">All Orders</div>
</div>
<% if @orders %>
 <%= will_paginate @orders%>
 <ul class="collapsible popout" data-collapsible="accordion">
  <li>
   <div class="collapsible-header">
     <ul class="row order-display title">
       <li class="col m1">Order</li>
       <li class="col m2">Owner</li>
       <li class="col m1">Total</li>
       <li class="col m2">Time Ordered</li>
       <li class="col m2"> PickUp Time</li>
       <li class="col m2">Status</li>
       <li class="col m1"></li>
     </ul>
   </div>
   <li>
   <% @orders.each do |order| %>
   <li>
     <div class="collapsible-header">
       <ul class="row order-display">
         <li class="col m1"> <%= order.id %></li>
         <li class="col m2"><%= order.employee.ename %></li>
         <li class="col m1">N<%= order.total || 0.0 %></li>
         <li class="col m2"><%= time_ago_in_words(order.created_at, include_seconds: true) + " ago"%></li>
         <li class="col m2"><%= time_ago_in_words((order.pickup_time).minutes.from_now)%></li>
         <%= form_for order, :url => {:controller => 'administrator', :action => 'update', order_id: order.id, status: order.Status }, method: :patch  do |f| %>
         <li class="col m2"><%= f.select :Status, options_for_status, selected: order.Status %></li>
          <li class="col m1"><%= f.submit "Confirm" %></li>
         <% end %>

       </ul>
     </div>
     <div class="collapsible-body">
       <table>
         <thead>
           <tr>
             <th data-field="name">Name</th>
             <th data-field="price">Price</th>
             <th data-field="sale-price">Sale Price</th>
             <th data-field="discount">Discount</th>
             <th data-field="quantity">Quantity</th>
           </tr>
         </thead>
         <tbody>
           <% order.order_items.each do |order_item| %>
           <% food = Food.find_by(order_item.food_id) %>
           <% if food %>
             <tr>
               <td><%=link_to "#{food.name}", food_path(food.id) %></td>
               <td><%= food.price %></td>
               <td><%= food.sales[:price] if food.sales[:status]%></td>
               <td><%= food.sales[:percentage] if food.sales[:status]%>%</td>
               <td><%= order_item.quantity %></td>
             </tr>
            <% end %>
         </tbody>
         <tfoot>

         </tfoot>
       <% end %>
       </table>
     </div>
   </li>
   <% end %>
 </ul>
<% else %>
 <div class="container">There are no orders to display</div>
<% end %>

app/views/administrator/_sales.html.erb
<div class="panel header-panel flow-text z-depth-3">
  <div id="title">All Sales</div>
</div>
<div class="full-height scroll-bar">
<div class="body">
    <table class="striped">
    <thead>
      <tr>
          <th data-field="id">Name</th>
          <th data-field="name">Description</th>
          <th data-field="price">Item Price</th>
          <th data-field="category">Category</th>
          <th data-field="status">Status</th>
          <th data-field="new_price">New Price</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |food| %>
        <a href = "/>">
        <tr>
          <td><%= food.name %></td>
          <td><%= food.description %></td>
          <td><%= food.price %></td>
          <td><%= !food.category.nil? ? food.category.title : "none yet" %></td>
          <td>
            <%= button_to "Remove", {}, :class => "remove_from_sale", "data-message" => food.id %>
          </td>
          <td><%= food.sales[:price]%></td>
        </tr>

      <% end %>
    </tbody>
  </table>
  </div>
  <div class="footer">
    <div class="row">
      <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
          <i class="large material-icons">add</i>
        </a>
        <ul>
          <li><a href="/sales/new" class="btn-floating yellow darken-1"><i class="material-icons">settings_input_svideo</i></a></li>
        </ul>
      </div>
    </div>
  </div>

</div>

app/views/administrator/category_index.js.erb
$('#show').html("<%=j render 'administrator/categories' %>"); 

app/views/administrator/employee_index.js.erb
$('#show').html("<%=j render 'administrator/users' %>"); 

app/views/administrator/food_index.js.erb
$('#show').html("<%=j render 'administrator/foods' %>"); 

app/views/administrator/order_index.js.erb
$('#show').html("<%=j render 'administrator/orders' %>"); 

app/views/administrator/sale_index.js.erb
$('#show').html("<%=j render 'administrator/sales' %>"); 
$('.remove_from_sale').click(function(){
     var food_id = $(this).data('message');
     var url = "/foods/" + food_id ;
     params = {
      food: {
        id: food_id,
        sales: {
          price: 0.0,
          percentage: 0,
          status: false,
          js: true
        } 
      }
     }
     var that = this.parentNode;
     ajax_call($(this), params, url, "PATCH", function(data){
      if (data.success){
        $(that).html("Removed from Sale");
      }
     });
  });
  
 
  var ajax_call = function(elem, params, url, method, callback){
    $.ajax({
      method: method,
      url: url,
      data: params,
      beforeSend: function(){

        elem.prop('disabled', true);
      },
      success: function(data){
        elem.prop('disabled', false);
        callback(data);
      },
      error: function(){
        Materialize.toast(elem.data('An error occured. Please try again'), 5000, 'rounded');
      },
      complete: function(){
      }
    });
  };

app/views/administrator/show.html.erb
<div class="row full-height">
 <%=render 'layouts/dashboard_menu' %>
 <div class="col s10 full-height scroll-bar">
    <div id="show">
      <%= render "administrator/orders" %>
    </div>
 </div>
</div>
</div>