config/routes.rb
Rails.application.routes.draw do
  get "sales/new"

  root "welcome#index"
  resources :foods do
    resources :comments
  end
  
  resources :categories
  resources :cart_items
  resources :carts
  resources :administrator
  resources :sales
  resources :employee do
    resources :orders
  end

  get "display/:option" => "sales#display", as: "display"
  get "login" => "welcome#new"
  get "/payment/processed" => "checkout#create", as: :get_payment_completed
  get "admin" => "administrator#show", as: :dashboard
  get "admin/foods" => "administrator#food_index", as: :admin_foods
  get "admin/orders" => "administrator#order_index", as: :admin_orders
  get "admin/employee" => "administrator#employee_index", as: :admin_employee
  get "admin/sales" => "administrator#sale_index", as: :admin_sales
  get "admin/categories" => "administrator#category_index",
      as: :admin_categories
  post "login" => "welcome#create"
  post "checkout" => "checkout#show", as: :checkout
  post "carts/checkout" => "carts#checkout", as: :cart_checkout
  post "payment" => "checkout#create", as: :payment
  post "/foods/:food_id/comments(.:format)" => "comments#create",
       as: :create_food_comment
  post "/payment/processed" => "checkout#create", as: :payment_completed
  patch "order_status" => "administrator#update", as: :order_status
  patch "/foods/:food_id/edit_status" => "foods#edit_status", as: :edit_status
  delete "logout" => "welcome#destroy"
  delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart
    attr_reader :cart_data

	def initialize(cart_data)
    @cart_data = cart_data || {}
	end

	def increment(item_id)
	  @cart_data[item_id] ||= 0
	  increment_cart_item_by_one(item_id)
	end

	def destroy
	  @cart_data = nil
	end

	def delete
		@cart_data[item_id] = 0
	end

	private

	def increment_cart_item_by_one(item_id)
	  @cart_data[item_id] += 1
	end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :foods
    has_one :sale
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :food
    belongs_to :employee
    validates :food_id,  presence: true
    validates :employee_id,  presence: true
end

app/models/current_order.rb
class CurrentOrder 
    attr_accessor :ordered_items
  attr_accessor :total
  attr_accessor :delivery_cost
  attr_accessor :sub_total
  attr_accessor :pickup_time

  def initialize(current_order)
    @ordered_items = current_order["items"] || {}
    current_order["details"] ||= {}
    @total = current_order["details"]["total"].to_i || 0
    @delivery_cost = 500
    @sub_total = current_order["details"]["sub_total"].to_i || 0
    @pickup_time = current_order["details"]["pickup_time"].to_i || 0
    @employee = {}
    @invoice = ""
    @transaction_id = ""
    @status = "pending"
  end

  def vat
    0.1 * @sub_total
  end

  def update_order(order, args)
    @ordered_items = order["items"] || {}
    @total = order["details"]["total"] || 0
    @pickup_time = order["details"]["pickup_time"].to_i || 0
    @total_pickup_time = add_extra_time(@pickup_time)
    @invoice = args[:invoice] || ""
    @transaction_id = args[:transaction_id] || ""
    @status = args[:status] || "pending"
  end

  def paypal_url(current_employee, return_url)
    @employee = current_employee
		values = {
			:business => 'tru2cent-facilitator@gmail.com',
			:cmd => '_cart',
			:upload => 1,
      :rm => 2,
			:return => return_url,
			# :invoice => 15,
      :notify_url => @employee.email,
      "amount_#{@ordered_items.length+1}" => vat,
      "item_name_#{@ordered_items.length+1}" => "VAT",
      "amount_#{@ordered_items.length+2}" => @delivery_cost,
      "item_name_#{@ordered_items.length+2}" => "Delivery cost"
		}
    counter = 1
		@ordered_items.each do |index, details|
			values.merge!({
				"amount_#{counter}" => details["food"]["price"],
				"item_name_#{counter}" => details["food"]["name"],
				"item_number_#{counter}" => counter,
				"quantity_#{counter}" => details["qty"]
			})
      counter += 1
		end
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
	end

  def save_order(current_employee)
    employee = current_employee
    new_order = employee.orders.new(total: @total, vat: vat,
                                delivery_cost: @delivery_cost,
                                invoice: @invoice,
                                transaction_id: @transaction_id,
                                pickup_time: @total_pickup_time)
    save_successful = new_order.save
    if save_successful
      @ordered_items.each do |index, details|
        new_order.order_items <<
          OrderItem.create(food_id: details["food"]["id"],
                           quantity: details["qty"])
      end
    end
    save_successful
  end

  def delete

  end

  private

  def add_extra_time(pick_up_time)
    if (Order.first.Status != "Delivered") || (Order.first.Status == "Cancelled")
       pick_up_time + 4
     else 
      pick_up_time
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
    
  validates :name,  presence: true, length: { maximum: 50 }
  validates :phone,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/food.rb
class Food < ApplicationRecord
    after_create :create_sale
    belongs_to :category
    has_many :order_items
    has_many :orders, through: :order_items
    serialize :sales

    has_attached_file :food_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "nigerian-jollof-rice.jpg"
    validates_attachment_content_type :food_image, :content_type => /\Aimage\/.*\Z/

    def create_sale
        self.sales = Hash.new
        sales[:price] = 0.00
        sales[:percentage] = 0
        sales[:status] = false
        save
    end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :foods, through: :order_items
  belongs_to :employee

  validates :transaction_id,  presence: true, uniqueness: { case_sensitive: false }
  default_scope{ order("created_at desc")}
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :food
    belongs_to :order
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/chef_helper.rb
module ChefHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    def log_in(user)
        session[:employee_id] = employee.id
        current_employee
      end
    
      def admin?
        if logged_in?
         current_employee.role == "admin"
        end
      end
    
      def current_employee
        @current_employee ||= Employee.find_by(id: session[:employee_id])
      end
    
      def logged_in?
        !current_employee.nil?
      end
    
      def log_out
        session.delete(:employee_id)
        @current_employee = nil
      end
    
      def check_if_admin
        if admin?
          true
        else 
          redirect_to root_path
          flash[:danger] = "You do not have access to the Admin page"
        end
      end
end

app/views/layouts/_category.html.erb
<center>
  <ul>
    <li>Categories</li>
    <% @categories = @categories.nil? ? Category.all : @categories %>
    <% @categories.each do |category| %>
      <li><%= link_to category.title, category_path(category) %></li>
    <% end %>
  </ul>
</center>

app/views/layouts/_dashboard_menu.html.erb
<div class="col s2 mini-pad z-depth-3 full-height scroll-bar table-cloth">
  <ul id="slide-out" class="side-nav fixed rel">
    <li class="first z-depth-1">Dashboard</li>
      <li><%= link_to "Foods",  admin_foods_path, :remote => true %></li>
      <li><%= link_to "Orders", admin_orders_path, :remote => true %></li>
      <li><%= link_to "Employees", admin_employees_path, :remote => true %></li>
      <li><%= link_to "Categories", admin_categories_path, :remote => true %></li>
      <li><%= link_to "Sales", admin_sales_path, :remote => true %></li>
  </ul>
</div>

app/views/layouts/_orders_page.html.erb
<ul class="collapsible popout" data-collapsible="accordion">
<li>
 <div class="collapsible-header">
   <ul class="row order-display title">
     <li class="col m2">Order</li>
     <li class="col m2">Total</li>
     <li class="col m2">Cost</li>
     <li class="col m4">Time</li>
     <li  class="col m2">Status</li>
   </ul>
 </div>
 <li>
 <% @orders.each do |order| %>
 <li>
   <div class="collapsible-header">
     <ul class="row order-display">
       <li class="col m2">Order: <%= order.id %></li>
       <li class="col m2">N<%= order.total || 0.0 %></li>
       <li class="col m2">N<%= order.delivery_cost || 0.0 %></li>
       <li class="col m4"><%= time_ago_in_words(order.created_at, include_seconds: true) + " ago" %></li>
       <li class="col m2"><%= order.Status %></li>
     </ul>
   </div>
   <div class="collapsible-body">
     <table>
       <thead>
         <tr>
           <th data-field="name">Name</th>
           <th data-field="price">Price</th>
           <th data-field="quantity">Quantity</th>
         </tr>
       </thead>
       <tbody>
         <% order.order_items.each do |order_item| %>
         <% food = Food.find(order_item.food_id) %>
           <% if food %>
             <tr>
               <td><%=link_to "#{food.name}", food_path(food.id) %></td>
               <td><%= food.price %></td>
               <td><%= order_item.quantity %></td>
             </tr>
           <% end %>
         <% end %>
       </tbody>
       <tfoot>

       </tfoot>

     </table>
   </div>
 </li>
 <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>